version: '3.8'
services:
  customer-app:
    image: app-javaspring-individual:latest
    restart: on-failure
    ports:
      - "4000:4000"
    networks:
      - network-javaspring-individualapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@localhost:1521/xe

networks:
  network-javaspring-individualapp:
    external: true